/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#8f0045',
        'surface-container-highest': '#353535',
        'on-secondary-fixed-variant': '#004f53',
        'on-tertiary-fixed': '#3f001b',
        'on-tertiary': '#65002f',
        'secondary-fixed-dim': '#00dce5',
        'secondary': '#e6feff',
        'inverse-surface': '#e2e2e2',
        'secondary-container': '#00f4fe',
        'outline-variant': '#434652',
        'tertiary-fixed-dim': '#ffb1c5',
        'surface-dim': '#131313',
        'primary': '#b1c5ff',
        'primary-container': '#0b3d91',
        'surface': '#131313',
        'on-secondary-container': '#006c71',
        'inverse-primary': '#345baf',
        'on-secondary': '#003739',
        'on-surface': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'on-background': '#e2e2e2',
        'surface-bright': '#393939',
        'surface-tint': '#b1c5ff',
        'on-primary': '#002c71',
        'tertiary-fixed': '#ffd9e1',
        'on-surface-variant': '#c4c6d3',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary-fixed-variant': '#144296',
        'tertiary-container': '#860040',
        'on-secondary-fixed': '#002021',
        'surface-container-low': '#1b1b1b',
        'inverse-on-surface': '#303030',
        'on-primary-container': '#8dadff',
        'on-error': '#690005',
        'surface-variant': '#353535',
        'outline': '#8e909d',
        'surface-container': '#1f1f1f',
        'surface-container-lowest': '#0e0e0e',
        'secondary-fixed': '#63f7ff',
        'background': '#131313',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'primary-fixed': '#dae2ff',
        'tertiary': '#ffb1c5',
        'on-primary-fixed': '#001947',
        'on-tertiary-container': '#ff8aad',
        'surface-container-high': '#2a2a2a',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
